name: TwoTowerRecEnv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - pip
  - pip:
      - faiss-cpu       # 可选（CPU 搜索 TopK 更快）
