preprocess:
  PROCESSED_DIR: "/content/drive/MyDrive/CS7643-GroupProject-Colab/processed"
train:
  batch_size: 512
  lr: 0.001
  num_epochs: 3
model:
  embedding_dim: 64
eval:
  topk_list: [10, 50, 100]
